export const DS = {
  colors: {
    bg:           '#F2EDE3',
    card:         '#FAF7F0',
    cardCream:    '#F7F2E8',
    accent:       '#8B3018',
    accentSoft:   '#B05A30',
    accentLight:  '#F0E4D8',
    accentPill:   '#E8D5C8',
    peach:        '#EDE0D4',
    text:         '#1A1008',
    textMid:      '#6B5140',
    textHint:     '#A08B76',
    sage:         '#5A7A54',
    sagePill:     '#E8F0E6',
    border:       '#C8B89A',
    white:        '#FFFFFF',
    red:          '#C04030',
  },
  radius: {
    card: 2,
    pill: 100,
    md:   4,
    sm:   2,
  },
  font: {
    regular: 'ShipporiMincho_400Regular',
    medium:  'ShipporiMincho_500Medium',
    semibold:'ShipporiMincho_600SemiBold',
    bold:    'ShipporiMincho_700Bold',
    heavy:   'ShipporiMincho_800ExtraBold',
  },
  home: {
    background: '#F2EDE3',
    card:       '#FAF7F0',
    pill:       '#EDE0D4',
    outline:    '#C8B89A',
    accent:     '#8B3018',
    text:       '#1A1008',
    textSoft:   '#6B5140',
    activeTab:  '#DDD0C0',
    radius: {
      photo: 2,
      panel: 4,
      pill:  100,
    },
    shadow: {
      shadowColor:   '#1A1008',
      shadowOffset:  { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius:  8,
      elevation:     3,
    },
  },
  shadow: {
    card: {
      shadowColor:   '#1A1008',
      shadowOffset:  { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius:  8,
      elevation:     2,
    },
    float: {
      shadowColor:   '#1A1008',
      shadowOffset:  { width: 0, height: 4 },
      shadowOpacity: 0.14,
      shadowRadius:  12,
      elevation:     6,
    },
  },
} as const;

export type DSColors = keyof typeof DS.colors;
