export const DS = {
  colors: {
    bg:           '#FAF6F0',
    card:         '#FFFFFF',
    cardCream:    '#FFF8F3',
    accent:       '#F07040',
    accentSoft:   '#F59468',
    accentLight:  '#FEF0E5',
    accentPill:   '#FDEADA',
    peach:        '#FBEEE4',
    pawWarm:      '#FFD4B8',
    text:         '#3B2314',
    textMid:      '#8B6347',
    textHint:     '#BBA898',
    sage:         '#6E9E68',
    sagePill:     '#EBF4EA',
    border:       '#EDE5DC',
    white:        '#FFFFFF',
    red:          '#E05040',
  },
  radius: {
    card: 20,
    pill: 100,
    md:   12,
    sm:   8,
  },
  font: {
    regular:  'MPLUSRounded1c_400Regular',
    medium:   'MPLUSRounded1c_500Medium',
    bold:     'MPLUSRounded1c_700Bold',
    heavy:    'MPLUSRounded1c_800ExtraBold',
    semibold: 'MPLUSRounded1c_700Bold',
  },
  home: {
    background: '#FAF6F0',
    card:       '#FFFFFF',
    pill:       '#FDE3C4',
    outline:    '#E8D4C2',
    accent:     '#F07040',
    text:       '#2C1A0E',
    textSoft:   '#8B6347',
    activeTab:  '#F5C4A0',
    radius: {
      photo: 20,
      panel: 20,
      pill:  999,
    },
    shadow: {
      shadowColor:  '#321905',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius:  18,
      elevation:     4,
    },
  },
  shadow: {
    card: {
      shadowColor:  '#50280A',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius:  14,
      elevation:     3,
    },
    float: {
      shadowColor:  '#50280A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.18,
      shadowRadius:  16,
      elevation:     8,
    },
  },
} as const;

export type DSColors = keyof typeof DS.colors;
